arb-dir: lib/src/l10n
template-arb-file: feedback_en.arb
output-localization-file: feedback_localizations.dart
output-class: FeedbackLocalizations
output-dir: lib/src/l10n/generated
synthetic-package: false
nullable-getter: false

