name: firestore_feedback
description: "A reusable Flutter feedback widget that submits user suggestions/bug reports to Firestore."
version: 0.2.3
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_bloc: ">=8.1.3 <11.0.0"
  equatable: ">=2.0.5 <3.0.0"
  intl: ">=0.18.0 <1.0.0"

  # Firebase
  cloud_firestore: ">=6.1.0 <9.0.0"

  # App metadata
  package_info_plus: ">=8.1.1 <11.0.0"


flutter:
  generate: true

